export const dummyRes = {
  etaList: [
    {
      stationId: "40320",
      stopId: "30062",
      stationName: "Division",
      platformName: "Service toward O'Hare",
      trainRunNumber: 124,
      abbreviatedRouteName: "Blue",
      destinationStationId: "0",
      destinationStationName: "O'Hare",
      trainDirectionCode: "1",
      timePredictionGenerated: "2023-09-09T23:35:41",
      arrivalTime: "2023-09-09T23:40:41",
      isApproaching: false,
      isBasedOnSchedule: true,
      isDelayed: true,
      hasFault: true,
    },
    {
      stationId: "40320",
      stopId: "30062",
      stationName: "Division",
      platformName: "Service toward O'Hare",
      trainRunNumber: 125,
      abbreviatedRouteName: "Blue",
      destinationStationId: "0",
      destinationStationName: "O'Hare",
      trainDirectionCode: "1",
      timePredictionGenerated: "2023-09-09T23:35:41",
      arrivalTime: "2023-09-09T23:52:41",
      isApproaching: false,
      isBasedOnSchedule: true,
      isDelayed: false,
      hasFault: false,
    },
    {
      stationId: "40320",
      stopId: "30063",
      stationName: "Division",
      platformName: "Service toward Forest Park",
      trainRunNumber: 131,
      abbreviatedRouteName: "Blue",
      destinationStationId: "0",
      destinationStationName: "UIC (for Forest Park)",
      trainDirectionCode: "5",
      timePredictionGenerated: "2023-09-09T23:35:34",
      arrivalTime: "2023-09-09T23:58:34",
      isApproaching: false,
      isBasedOnSchedule: false,
      isDelayed: false,
      hasFault: false,
      latitude: 41.90336,
      longitude: -87.6665,
      directionDegree: 123,
    },
    {
      stationId: "40320",
      stopId: "30063",
      stationName: "Division",
      platformName: "Service toward Forest Park",
      trainRunNumber: 133,
      abbreviatedRouteName: "Blue",
      destinationStationId: "0",
      destinationStationName: "Forest Park",
      trainDirectionCode: "5",
      timePredictionGenerated: "2023-09-09T23:35:40",
      arrivalTime: "2023-09-10T00:18:40",
      isApproaching: false,
      isBasedOnSchedule: true,
      isDelayed: false,
      hasFault: false,
    },
  ],
  errorCode: "0",
  errorDescription: null,
  timePredictionGenerated: "2023-09-09T22:31:28",
};
